### ISSUE TITLE
websoket bug

### ISSUE THREAD

**Issue by xingxichen** [ctlove0523/gotify-java-client#2]
endpoint("http://xxx.com/gotify") 这种地址无法连接上websoket

**Comment by ctlove0523** [comment]
有没有具体的业务场景或者能够复现issue的样例代码？

**Comment by xingxichen** [comment]
Credential credential = new BasicCredential.Builder()
                .userName("admin")
                .password("admin")
                .build();

        // config gotify server listen address and port.
        GotifyClientConfig config = new GotifyClientConfig.Builder()
                .endpoint("http://xxx.xxx/gotify")
                .credential(credential)
                .build();
        GotifyClient gotifyClient = GotifyClient.build(config);
        MessageClient messageClient = gotifyClient.getMessageClient();
        messageClient.registerMessageHandler(message -> {
            System.out.println(JSONUtil.formatJsonStr(JSONUtil.toJsonStr(message)));
        });
在同一个服务器通过nginx根据请求前缀转发到不同端口

**Comment by ctlove0523** [comment]
> 

使用你的示例代码可以连接gotify server并能收到消息推送。你的问题可能和nginx的配置相关

**Comment by xingxichen** [comment]
![image](https://user-images.githubusercontent.com/50514349/159166688-bd822660-fb14-49c8-8f16-d5d2b0dea205.png)
你这里这个uri最后只有端口号没有加上path吧,我改了下就连上了

**Comment by ctlove0523** [comment]
根据官方API[文档](https://gotify.net/api-docs#/message/streamMessages) 通过WS获取消息连接的URL为`/stream`，但是你的场景使用了Nginx作为反向代理并根据请求的前缀转发请求，所以连接`ws://host:port/gotify/stream`，经过Nginx转发后实际为`ws://host:port/stream`。你可以提交一个PR以支持这种代理场景。

**Comment by ctlove0523** [comment]
使用messagePath方法配置接收消息的WS路径以取代默认值/stream
~~~java
GotifyClientConfig config=new GotifyClientConfig.Builder()
	.endpoint("http://localhost")
	.credential(credential)
	.messagePath("/nginx/stream")
	.build();
~~~
